name = "ed-paintboard"
main = "src/index.js"
compatibility_date = "2024-04-03"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "ED_PB_KV"
id = "9becaa302e5d4aeaa374a2ef2a4c558c"

[[durable_objects.bindings]]
name = "WEBSOCKET_HANDLER"
class_name = "WebSocketHandler"

[unsafe]
allow = ["rpc"]

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHandler"]