name = "paintboard" # 项目名称
main = "src/index.js"
compatibility_date = "2024-04-03"

[assets]
directory = "public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "PaintBoard_KV" # 你的 KV 命名空间的名称
id = "xxx" # 命名空间的 ID

[[durable_objects.bindings]]
name = "WEBSOCKET_HANDLER"
class_name = "WebSocketHandler"

[unsafe]
allow = ["rpc"]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHandler"]

route = "example.com/*" # 替换成你的域名